"""
Coding Standards
================
Maximum allowed values for each coding category from the DiKoBi coding manual.
"""

# Maximum allowed values for each category
MAX_VALUES = {
    # Fall 1: Unterrichtseinstieg
    '1_D_M': 2,
    '1_D_N': float('inf'),  # Anzahl - no maximum
    '1_D_PCK': 2,
    '1_D_PK': 2,
    '1_D_kA': 2,
    '1_Dm_M': 2,
    '1_Dm_PCK': 2,
    '1_Dm_PK': 2,
    '1_Dm_kA': 2,
    '1_E_T_IV': 3,
    '1_E_T_PCK': 3,
    '1_E_T_PK': 3,
    '1_P_PCK': 1,
    '1_P_PK': 1,
    '1_W': 1,
    
    # Fall 2: Schülerfehlvorstellungen
    '2_D': 2,
    '2_D_PCK': 2,
    '2_D_SF1': 2,
    '2_D_SF2': 2,
    '2_D_USF': 2,
    '2_E_IV': 3,
    '2_E_PCK': 3,
    '2_Pha': 3,
    '2_Pv_PCK': 1,
    
    # Fall 3: Fachsprache
    '3_D': 2,
    '3_D_Ep': 2,
    '3_D_F': 2,
    '3_D_N': float('inf'),  # Anzahl - no maximum
    '3_D_PCK': 2,
    '3_D_PK': 2,
    '3_D_Qual': 2,
    '3_D_Quan': 2,
    '3_Dm_Ep': 2,
    '3_Dm_F': 2,
    '3_Dm_Kons': 2,
    '3_Dm_PCK': 2,
    '3_Dm_PK': 2,
    '3_Dm_Qual': 2,
    '3_Dm_Quan': 2,
    '3_E_PCK': 3,
    '3_E_T_IV': 3,
    '3_E_T_PCK': 3,
    '3_E_T_PK': 3,
    '3_P_PCK': 1,
    '3_P_PK': 1,
    '3_Pha': 3,
    '3_Pha_F': 3,
    '3_Pha_Kons': 3,
    '3_Pha_PCK': 3,
    '3_Pha_Qual': 3,
    '3_Pha_Quan': 3,
    '3_Pv_PCK': 1,
    '3_W': 1,
    
    # Fall 4: Experimente
    '4_D': 2,
    '4_D_Ep': 2,
    '4_D_F': 2,
    '4_D_N': float('inf'),  # Anzahl - no maximum
    '4_D_PCK': 2,
    '4_D_PK': 2,
    '4_D_Qual': 2,
    '4_D_Quan': 2,
    '4_Dm_Ep': 2,
    '4_Dm_F': 2,
    '4_Dm_Kons': 2,
    '4_Dm_PCK': 2,
    '4_Dm_PK': 2,
    '4_Dm_Qual': 2,
    '4_Dm_Quan': 2,
    '4_E_PCK': 3,
    '4_E_T_IV': 3,
    '4_E_T_PCK': 3,
    '4_E_T_PK': 3,
    '4_P_PCK': 1,
    '4_P_PK': 1,
    '4_Pha': 3,
    '4_Pha_Ep': 3,
    '4_Pha_PCK': 3,
    '4_Pv_PCK': 1,
    '4_W': 1,
    
    # Fall 5: Modelle
    '5_D': 2,
    '5_D_Ma': 2,
    '5_D_Mk': 2,
    '5_D_N': float('inf'),  # Anzahl - no maximum
    '5_D_PCK': 2,
    '5_D_PK': 2,
    '5_Dm_Ma': 2,
    '5_Dm_Mk': 2,
    '5_Dm_PCK': 2,
    '5_Dm_PK': 2,
    '5_E_IV': 3,
    '5_E_PCK': 3,
    '5_E_T_IV': 3,
    '5_E_T_PCK': 3,
    '5_E_T_PK': 3,
    '5_P_PCK': 1,
    '5_P_PK': 1,
    '5_Pha': 3,
    '5_Pha_Ma': 3,
    '5_Pha_Mk': 3,
    '5_Pha_PCK': 3,
    '5_Pv_PCK': 1,
    '5_W': 1,
    
    # Fall 6: Sicherung/Transfer
    '6_D': 2,
    '6_D_N': float('inf'),  # Anzahl - no maximum
    '6_D_PCK': 2,
    '6_D_PK': 2,
    '6_D_Rb': 2,
    '6_D_kA': 2,
    '6_Dm_PCK': 2,
    '6_Dm_PK': 2,
    '6_Dm_Rb': 2,
    '6_Dm_kA': 2,
    '6_E_IV': 3,
    '6_E_PCK': 3,
    '6_E_T_IV': 3,
    '6_E_T_PCK': 3,
    '6_E_T_PK': 3,
    '6_P_PCK': 1,
    '6_P_PK': 1,
    '6_P_T_PCK': 1,
    '6_Pha': 3,
    '6_Pha_PCK': 3,
    '6_Pha_Rb': 3,
    '6_Pha_kA': 3,
    '6_Pv_PCK': 1,
    '6_W': 1,
}
